Resources:
  myuserpoolmglabeksdemo:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes: []
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      SmsVerificationMessage: The verification code to your new account is {####}
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      UserPoolName: eks-demo-oidc-userpool
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  myuserpooloidcclientmglabeksdemo:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: myuserpoolmglabeksdemo
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - profile
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://example.com
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO

  myuserpoolCognitoDomainmglabeksdemo:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Join
        - "-"
        - - "mglab-oidc-userpool"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      UserPoolId:
        Ref: myuserpoolmglabeksdemo


Outputs:
  IssuerUrl:
    Value:
      Fn::Join:
        - ""
        - - https://cognito-idp.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: myuserpoolmglabeksdemo
  PoolId:
    Value:
      Ref: myuserpoolmglabeksdemo
  ClientId:
    Value:
      Ref: myuserpooloidcclientmglabeksdemo
