apiVersion: constraints.gatekeeper.sh/v1beta1
kind: opa-container-limits
metadata:
  name: container-must-have-limits
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "400m"
    memory: "1Gi"
