---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
type: Opaque
data:
  username: Z3JhZmFuYQ==
  passphrase: R3JhZmFuYVBAc3N3MHJk
---
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: a2lhbGk=
  passphrase: S2lhbGlQQHNzdzByZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger
  namespace: istio-system
  labels:
    app: jaeger
type: Opaque
data:
  username: amFlZ2Vy
  passphrase: SmFlZ2VyUEBzc3cwcmQ=
